language: c
compiler:
  - gcc
  - clang
before_install:
 - # Build dependencies for libgdata, libsoup-2.4 and json-glib-1.0
 - sudo apt-get update -qq
 - sudo apt-get install -qq libglib2.0-dev libxml2-dev libsoup2.4-dev libjson-glib-dev liboauth-dev libgdk-pixbuf2.0-dev gnome-common gtk-doc-tools gobject-introspection valac libgcr-3-dev libgoa-1.0-dev
 - mkdir deps
 - export PKG_CONFIG_PATH=./deps:$PKG_CONFIG_PATH
 - # Need automake-1.13.4 for GLib; install it system wide as it is parallel-installable
 - wget ftp://ftp.gnu.org/gnu/automake/automake-1.13.4.tar.xz
 - tar -xvJf automake-1.13.4.tar.xz
 - cd automake-1.13.4
 - ./configure && make && sudo make install
 - cd ..
 - # Need GLib 2.36 for libsoup-2.4, but Ubuntu 12.04 only provides 2.32
 - wget http://ftp.gnome.org/pub/GNOME/sources/glib/2.36/glib-2.36.4.tar.xz
 - tar xvJf glib-2.36.4.tar.xz
 - cd glib-2.36.4
 - ./configure --prefix=../deps && make && sudo make install
 - cd ..
 - # Need libsoup-2.4 > 2.42, but Ubuntu 12.04 only provides 2.38
 - wget http://ftp.gnome.org/pub/GNOME/sources/libsoup/2.42/libsoup-2.42.3.tar.xz
 - tar xvJf libsoup-2.42.3.tar.xz
 - cd libsoup-2.42.3
 - ./configure --prefix=../deps && make && sudo make install
 - cd ..
 - # Need json-glib-1.0 > 0.15, but Ubuntu 12.04 only provides 0.14
 - wget http://ftp.gnome.org/pub/GNOME/sources/json-glib/0.16/json-glib-0.16.2.tar.xz
 - tar xvJf json-glib-0.16.2.tar.xz
 - cd json-glib-0.16.2
 - ./configure --prefix=../deps && make && sudo make install
 - cd ..
 - # Actually build libgdata
script: ./autogen.sh --enable-gnome --enable-goa --enable-compile-warnings=error --enable-introspection --enable-vala --enable-gtk-doc && make && make check
